var regLink=false;var tid=getPARAM('tid');getAdvData();$(function(){/*$('.main-offer-img').click(doRegistration);*//*$('.inner-steps').click(doRegistration);*/$('.logo').click(function(e){e.preventDefault();doRegistration(e);});setInterval(function(){var imgContainer=$('.main-offer-img'),oldImg=imgContainer.css('background-image'),newImg=imgContainer.data('img');imgContainer.data('img',oldImg);imgContainer.css('background-image',newImg);},4000);});function shootPixel(callback){var pixelUrl='https://record.eshkol.com/_q5h4xISYMFhDp78Ph1_jCGNd7ZgqdRLk/1/?payload=PTM_FallBack_{traffic_source}_{zone}_{tid}';pixelUrl=pixelUrl.replace('{tid}',getPARAM('tid')).replace('{zone}',getPARAM('zone')).replace('{traffic_source}',getPARAM('traffic_source'));$('body').append('<iframe id="clickpixel" src="'+ pixelUrl+'" width="1px" height="1px" style="position: absolute;bottom: 0;left:0;"></iframe>');document.getElementById('clickpixel').onload=function(){callback();};}
function getPARAM(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?&]"+ name+"=([^&#]*)"),results=regex.exec(location.search);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "));}
function startNG(){$.holdReady(true);var ifra=document.createElement('iframe');ifra.style.position='absolute';ifra.src=visitScript+"&AR="+ readAdvCookie("ar")+"&PAR="+ readAdvCookie("par");ifra.setAttribute("height","1");ifra.setAttribute("width","1");ifra.setAttribute("frameborder","0");document.body.appendChild(ifra);var tk=document.createElement('script');tk.src=regScript;tk.type='text/javascript';tk.onload=tk.onreadystatechange=function(){var rs=this.readyState;if(rs&&rs!='complete'&&rs!='loaded')return;try{ng_fw.init();}catch(e){}};document.body.appendChild(tk);}
function doLpReg(){ng_fw.init();_ng_fw.JoinNowUser();}
function doRegistration(e){if(e){e.preventDefault();}
if(regLink!==false){location.href=regLink;}else{if(tid){shootPixel(function(){location.href=mainSite+"?neodl=registration&"+"AR="+ readAdvCookie("ar")+"&PAR="+ readAdvCookie("par")+'#register';});}else{location.href=mainSite+"?neodl=registration&"+"AR="+ readAdvCookie("ar")+"&PAR="+ readAdvCookie("par")+'#register';}}}
function rewriteAdvCookie(name,value,days){var expires;if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires=";expires="+ date.toGMTString();}else{expires="";}
document.cookie=name+"="+ value+ expires+";domain=.magicred.com;path=/";}
function readAdvCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;}
function getAdvData(){var queryDict={},defAr="",defPar="-cW_fFRpXONVDQsR8vgoqWNd7ZgqdRLk";location.hash.substr(1).split("&").forEach(function(item){queryDict[item.split("=")[0]]=item.split("=")[1];});if(typeof queryDict["ar"]!=='undefined'){defAr=queryDict["ar"];}
if(typeof queryDict["par"]!=='undefined'){defPar=queryDict["par"];}
if(defAr==="177"){regLink="http://traffic.focuusing.com/process?"+ location.hash.substr(1)+"&direct=1";if(regLink.indexOf("&code=")!==-1){regLink=regLink.replace("&code=","&r_code=");}}
if(readAdvCookie("ar")===null){rewriteAdvCookie("ar",encodeURIComponent(defAr),60);}
if(readAdvCookie("par")===null){rewriteAdvCookie("par",encodeURIComponent(defPar),60);}}
var oldDocumentWrite=document.write;document.write=function(html){if(html.indexOf("<script")!==-1){var firstChar=html.substr(html.indexOf('src=')+ 4,1),src=html.substr(html.indexOf('src=')+ 5,html.length);src=src.substr(0,src.indexOf(firstChar));var tk=document.createElement('script');tk.src=src;tk.type='text/javascript';tk.onload=tk.onreadystatechange=function(){var rs=this.readyState;if(rs&&rs!='complete'&&rs!='loaded')return;try{if(typeof _ng_fw!=="undefined"&&typeof ng_fw!=="undefined"&&typeof _ng_fw_customization!=="undefined"&&typeof _ng_fw_customization.getNotifierAllowedEvents!=="undefined"){$.holdReady(false);ng_fw.init();}}catch(e){}};document.body.appendChild(tk);}else{oldDocumentWrite.call(document,html);}};